main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='home'),
    path('register/', views.registerUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
]

storyproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("story4/", include('story4.urls')),
    path('', include('main.urls')),
    path('story1/', include('story1.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    username = forms.CharField(label="Username", max_length=150, widget=forms.TextInput(attrs=
    {
        'class' : 'form-control',
        'placeholder' : 'Username',
    }))

    email = forms.EmailField(label="email", max_length=150, widget=forms.TextInput(attrs=
    {
        'class' : 'form-control',
        'placeholder' : 'Email',
    }))

    password1 = forms.CharField(label="Password", max_length=150, widget=forms.PasswordInput(attrs=
    {
        'class' : 'form-control',
        'placeholder' : 'Password',
    }))

    password2 = forms.CharField(label="Confirm Password", max_length=150, widget=forms.PasswordInput(attrs=
    {
        'class' : 'form-control',
        'placeholder' : 'Confirm Password',
    }))

story9/views.py
from django.shortcuts import render, redirect
from .forms import CreateUserForm
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

def index(request):
    context = {}
    return render(request, 'story9/home.html', context)

def registerUser(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account was succesfully created')
            return HttpResponseRedirect('/story9/login')
        else:
            messages.error(request, 'Account creation was unsuccessful')
    context = {
        'form' : form
    }
    return render(request, 'story9/register.html', context)

def loginUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Login successful')
            return redirect('/story9/')
        else:
            messages.error(request, 'Username or Password is incorrect')
    context = {}
    return render(request, 'story9/login.html', context)

def logoutUser(request):
    logout(request)
    messages.success(request, 'Logout successful')
    return redirect('/story9/')

story9/templates/story9/home.html
{% extends 'story9/story9.html' %}
{% load static %}

{% block content %}

<section>
    {% include 'story9/messages.html' %}
    <div class="login">
        {% if request.user.username == '' %}
        <h1>Welcome, Anonymous</h1>
        {% else %}
        <h1>Welcome, {{ request.user }}</h1>
        {% endif %}

    </div>
</section>
{% endblock %}

story9/templates/story9/login.html
{% extends 'story9/story9.html' %}
{% load static %}

{% block content %}

<section>
    {% include 'story9/messages.html' %}
    <div class="kotak">
        

        <h1>Login</h1>
        <form class="form" action="" method="POST">
            {% csrf_token %}
            <input type="text" placeholder="Username" name="username" required>
            <input type="password" placeholder="Password" name="password" required>
            <button class="button" type="submit">Login</button>
        </form>
        <p>Don't have an account? <a href="{% url 'story9:register' %}" class="heh">Sign Up</a></p>

    </div>
</section>
{% endblock %}

story9/templates/story9/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'error'%}
        <div class="alert alert-{{ message.tags }} m-2" id="msg" role="msg">
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-{{ message.tags }} m-2" id="msg" role="msg">
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

story9/templates/story9/register.html
{% extends 'story9/story9.html' %}
{% load static %}

{% block content %}

<section>
    {% include 'story9/messages.html' %}
    <div class="kotak">
        <h1>Register</h1>
        <form class="form" action="" method="POST">
            {% csrf_token %}

            {{ form.username }}

            {{ form.email }}

            {{ form.password1 }}

            {{ form.password2 }}

            {% for error in form.password2.errors %}
                <p class="validation">{{ error }}</p>
            {% endfor %}
            <button class="button" type="submit">Sign Up</button>
        </form>
    </div>
</section>
{% endblock %}

story9/templates/story9/story9.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adimas</title>
    <link rel="icon" href="/static/resource/A.svg" type="image/x-icon">
    <link rel="stylesheet" href="/static/css/stylesheet.css">
    <link rel="stylesheet" href="/static/css/story5.css">
    <link rel="stylesheet" href="/static/story9.css">
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
</head>
<body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <nav>
        <div class="logo"><a href="{% url 'main:home' %}"><img src="{% static 'resource/ADIMAS.svg' %}" alt="logo"></a></div>
        <div class="menu_navbar">
            <div class="desktop">
                {% if request.user.username == '' %}
                <a href="{% url 'story9:login' %}">Login</a>
                {% else %}
                <a href="{% url 'story9:logout' %}">Logout</a>
                {% endif %}
                
            </div>
            <div class="mobile">
                <a class="burger-button"><img src="/static/resource/burger.svg" alt=""></a>
                <div class="burger-menu burger-hide" id="burger-menu">
                    {% if request.user.username == '' %}
                    <a href="{% url 'story9:login' %}">Login</a>
                    {% else %}
                    <a href="{% url 'story9:logout' %}">Logout</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    
    {% block content %}

    {% endblock %}

    <script>
        setTimeout(function(){
            if ($('#msg').length > 0) {
                $('#msg').remove()
            }
        }, 3000)
    </script>
    <!-- <script src="/static/story8.js" defer></script> -->
</body>
</html>