main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story4/urls.py
from django.urls import path
from . import views

app_name = 'story4'

urlpatterns = [
    path('', views.story4, name='home'),
    path("poster", views.poster, name='poster'),
    path("website", views.website, name='website')
]

storyproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("story4/", include('story4.urls')),
    path('', include('main.urls')),
    path('story1/', include('story1.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story4/models.py
from django.db import models

# Create your models here.

story4/views.py
from django.shortcuts import render

# Create your views here.
def story4(request):
    return render(request, 'story4/home.html')

def poster(request):
    return render(request, 'story4/poster.html')

def website(request):
    return render(request, 'story4/website.html')

story4/templates/story4/baseStory4.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adimas</title>
    <link rel="icon" href="/static/resource/A.svg" type="image/x-icon">
    <link rel="stylesheet" href="/static/css/stylesheet.css">
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
</head>
<body>
    {% include 'story4/navbar.html' %}

    {% block content %}
    {% endblock %}

    {% include 'story4/footer.html' %}
    <script src="/static/script/main.js"></script>
</body>
</html>

story4/templates/story4/footer.html
{% load static %}

<footer>
    <p>Copyright ©2020 All rights reserved<br>This website is made by Adimas Putra Pratama Hendrata</p>
</footer>

story4/templates/story4/home.html
{% extends 'story4/baseStory4.html' %}
{% load static %}

    
{% block content %}
    <main>
        <div class="destop">
            <div class="overlay">
                <div class="overlay-1">FRONTEND</div>
                <div class="overlay-2">UI/UX</div>
            </div>
        </div>

        <section class="section-1">
            <div class="kiri">
                <h3>Hi, I'm Adimas Putra Pratama Hendrata</h3>
                <h1>UI/UX Designer and<br>Graphic Designer</h1>
                <img id="about-me" src="/static/resource/kotak5.svg" alt="">
            </div>
            <div class="kanan">
                <img class="foto-profile" src="/static/resource/profpic.jpg" alt="">
            </div>
        </section>

        <section class="section-2">
            <div class="about-me">
                <h2>About Me.</h2>
                <p>
                    Saya adalah seorang Graphic Designer dan juga UI/UX Designer, sekarang saya sedang kuliah di Universitas Indonesia jurusan Sistem Informasi. Saya telah belajar mendesain sejak awal SMA. Awal mula perjalanan saya dalam belajar desain saat membuat poster. Saat ini saya sedang belajar menjadi Frontend Developer untuk menjadi Fullstack Developer Saya adalah orang yang supel dan mudah bergaul dengan orang lain. Sangat ambisius dan bertanggung jawab dalam mengerjakan sesuatu yang telah dimulai. 
                </p>
                <div class="sosmed">
                    <!-- <h2>Contact.</h2> -->
                    <a href="http://line.me/ti/p/~adimas11" class="butsosmed line">
                        <img src="/static/resource/asset/line.svg" alt="">
                        <div class="hide">@adimas11</div>
                    </a>
                    <a href="https://www.instagram.com/adimaspph" class="butsosmed ig">
                        <img src="/static/resource/asset/instagram.svg" alt="">
                        <div class="hide">@adimaspph</div>
                    </a>
                    <a href="https://wa.me/081519327044" class="butsosmed wa">
                        <img src="/static/resource/asset/whatsapp.svg" alt="">
                        <div class="hide">081519327044</div>
                    </a>
                    <a href="mailto:adimas.putra@ui.ac.id" class="butsosmed email">
                        <img src="/static/resource/asset/email 2.svg" alt="">
                        <div class="hide">adimas.putra@ui.ac.id</div>
                    </a>
                    
                </div>
            </div>
            <div class="skills">
                <h2>Skills.</h2>
                <div class="skill">
                    <img src="/static/resource/figma.png" alt="">
                    <img src="/static/resource/html.png" alt="">
                    <img src="/static/resource/css.png" alt="">
                    <img src="/static/resource/ps.png" alt="">
                    <img src="/static/resource/ai.png" alt="">
                    <img src="/static/resource/pr.png" alt="">
                </div>
            </div>
        </section>
        
        <section class="section-3">
            <div class="title">
                <H1>My Project</H1>
            </div>
            <h2 class="galeri-type">Project Poster.</h2>
            <div class="poster">
                <div class="col1"> 
                    <img src="/static/resource/Gallery/1.jpg" alt="">                        
                </div>

                <div class="col2">
                    <img src="/static/resource/Gallery/2.jpg" alt="">
                </div>

                <div class="col3">
                    <img src="/static/resource/Gallery/3.jpg" alt="">
                </div>
            </div>
            <div class="link">
                <a href="{% url 'story4:poster' %}" class="button">Explore My Poster Project</a>
            </div>

            <h2 class="galeri-type">Project Website.</h2>
            <div class="website">
                <img src="/static/resource/Gallery/WebOH.jpg" alt="">
                <img src="/static/resource/Gallery/web1.png" alt="">
            </div>
            
            <div class="link">
                <a href="{% url 'story4:website' %}" class="button">Explore My Website Project</a>
            </div>
        </section>
    </main>

{% endblock %}

story4/templates/story4/navbar.html
{% load static %}

<nav>
    <div class="logo"><a href="{% url 'main:home' %}"><img src="{% static 'resource/ADIMAS.svg' %}" alt="logo"></a></div>
    <div class="menu_navbar">
        <div class="desktop">
            <a href="{% url 'story4:home' %}">Home</a>
            <a href="{% url 'story4:poster' %}">My Poster</a>
            <a href="{% url 'story4:website' %}">My Website</a>
        </div>
        <div class="mobile">
            <a class="burger-button"><img src="/static/resource/burger.svg" alt=""></a>
            <div class="burger-menu burger-hide" id="burger-menu">
                <a href="{% url 'story4:home' %}">Home</a>
                <a href="{% url 'story4:poster' %}">My Poster</a>
                <a href="{% url 'story4:website' %}">My Website</a>
            </div>
        </div>
    </div>
</nav>

story4/templates/story4/poster.html
{% extends 'story4/baseStory4.html' %}
{% load static %}

{% block content %}
<div class="galeri">
    <div class="title">
        <h1>My Project</h1>
    </div>
    <div class="selector">
        <h2 style="text-decoration: underline">Poster</h2>
        <a href="{% url 'story4:website' %}"><h2 class="pencet">Website</h2></a>
    </div>
    <div class="poster">
        <div class="col1"> 
            <img src="/static/resource/Gallery/1.jpg" alt="">                        
            <img src="/static/resource/Gallery/4.jpg" alt="">
            <img src="/static/resource/Gallery/6.jpg" alt="">
            <img src="/static/resource/Gallery/7.jpg" alt="">
            <img src="/static/resource/Gallery/14.jpg" alt="">
            <img src="/static/resource/Gallery/18.jpg" alt="">
            <img src="/static/resource/Gallery/19.jpg" alt="">
        </div>

        <div class="col2">
            <img src="/static/resource/Gallery/2.jpg" alt="">
            <img src="/static/resource/Gallery/16.jpg" alt="">
            <img src="/static/resource/Gallery/8.jpg" alt="">
            <img src="/static/resource/Gallery/11.jpg" alt="">
            <img src="/static/resource/Gallery/15.jpg" alt="">
        </div>

        <div class="col3">
            <img src="/static/resource/Gallery/3.jpg" alt="">
            <img src="/static/resource/Gallery/5.jpg" alt="">
            <img src="/static/resource/Gallery/12.jpg" alt="">
            <img src="/static/resource/Gallery/13.jpg" alt="">
            <img src="/static/resource/Gallery/17.jpg" alt="">
            <img src="/static/resource/Gallery/20.jpg" alt="">
        </div>
    </div>
</div>
{% endblock %}

story4/templates/story4/website.html
{% extends 'story4/baseStory4.html' %}
{% load static %}

{% block content %}

<div class="galeri">
    <div class="title">
        <h1>My Project</h1>
    </div>
    
    <div class="selector">
        <a href="{% url 'story4:poster' %}"><h2  class="pencet">Poster</h2></a>
        </a><h2 style="text-decoration: underline">Website</h2>
    </div>

    <div class="website">
        <img src="/static/resource/Gallery/WebOH.jpg" alt="">
        <img src="/static/resource/Gallery/web1.png" alt="">
    </div>
    
</div>

{% endblock %}