main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story4/urls.py
from django.urls import path
from . import views

app_name = 'story4'

urlpatterns = [
    path('', views.story4, name='home'),
    path("poster", views.poster, name='poster'),
    path("website", views.website, name='website')
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.story5, name='home'),
    path('add/', views.add, name='add'),
    path('<int:my_id>/', views.detail, name='detail'),
    path('<int:my_id>/delete/', views.delete_matkul, name='delete'),
]

storyproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("story4/", include('story4.urls')),
    path('', include('main.urls')),
    path('story1/', include('story1.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story5/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.

class Matkul(models.Model):
    nama_matkul = models.CharField(max_length=30)
    dosen = models.CharField(max_length=30)
    sks = models.CharField(max_length=2)
    tahun = models.CharField(max_length=30)
    deskripsi = models.TextField(max_length=150)
    ruang = models.CharField(max_length=30)

class Post(models.Model):
    author = models.ForeignKey(Matkul, on_delete = models.CASCADE)
    content = models.CharField(max_length=500)
    published_date = models.DateTimeField(default=timezone.now)

story5/forms.py
from django import forms
from . import models

# from .models import Matkul
class Form_Matkul(forms.ModelForm):
    class Meta:
        model = models.Matkul
        fields = [
            'nama_matkul',
            'dosen',
            'sks',
            'tahun',
            'deskripsi',
            'ruang',
        ]

    error_message = {
        'required' : "Mohon masukan sesuatu"
    }

    nama_matkul = forms.CharField(
        max_length=30, widget=forms.TextInput(attrs = {
        'placeholder': 'Nama Mata Kuliah',
        'type' : 'text',
        }))

    dosen = forms.CharField(max_length=30, widget=forms.TextInput(attrs = {
        'placeholder': 'Nama Dosen',
        'type' : 'text',
        }))

    sks = forms.CharField(max_length=30, widget=forms.TextInput(attrs = {
        'placeholder': 'SKS',
        'type' : 'number',
        'min' : "1",
        'max' : "24",
        }))

    tahun = forms.CharField(max_length=30, widget=forms.TextInput(attrs = {
        'placeholder': 'Gasal 2000/2001',
        'type' : 'text',
        }))

    deskripsi = forms.Textarea(attrs = {
        'placeholder': 'Deskripsi Mata Kuliah',
    })

    ruang = forms.CharField(max_length=30, widget=forms.TextInput(attrs = {
        'placeholder': 'Ruagan',
        'type' : 'text',
        }))

story5/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from . import models
from .forms import Form_Matkul

# Create your views here.
def story5(request):
    matkuls = models.Matkul.objects.all()
    response = {
        "matkuls" : matkuls,
    }

    return render(request, 'story5/home.html', response)

def add(request):
    form = Form_Matkul(request.POST or None)
    response = {
        "form_matkul" : Form_Matkul,
    }
    
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/story5/')
    return render(request, 'story5/add.html', response)

def detail(request, my_id):
    obj = models.Matkul.objects.get(id = my_id)
    response = {
        "obj" : obj
    }

    return render(request, 'story5/detail.html', response)

def delete_matkul(request, my_id):
    obj = models.Matkul.objects.get(id = my_id)
    obj.delete()
    return HttpResponseRedirect('/story5/')

story5/templates/story5/add.html
{% extends 'story5/baseStory5.html' %}
{% load static %}
{% block content %}

<section>
    <h1>Menambah Matkul</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <table class="input-form" >
            <tr>
                <th><label for="">Nama Mata Kuliah:</label></th>
                <th>{{ form_matkul.nama_matkul }}</th>
            </tr>
            <tr>
                <th><label for="">Nama Dosen:</label></th>
                <th>{{ form_matkul.dosen }}</th>
            </tr>
            <tr>
                <th><label for="">Jumlah SKS:</label></th>
                <th>{{ form_matkul.sks }}</th>
            </tr>
            <tr>
                <th><label for="">Tahun:</label></th>
                <th>{{ form_matkul.tahun }}</th>
            </tr>
            <tr>
                <th><label for="">Deskripsi:</label></th>
                <th>{{ form_matkul.deskripsi }}</th>
            </tr>
            <tr>
                <th><label for="">Ruang</label></th>
                <th>{{ form_matkul.ruang }}</th>
            </tr>
            <tr>
                <th></th>
                <th><button type="submit" class="button">Tambah Matkul</button></th>
            </tr>
        </table>
        
    </form>
</section>


{% endblock %}

story5/templates/story5/baseStory5.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adimas</title>
    <link rel="icon" href="/static/resource/A.svg" type="image/x-icon">
    <link rel="stylesheet" href="/static/css/stylesheet.css">
    <link rel="stylesheet" href="/static/css/story5.css">
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
</head>
<body>
    <nav>
        <div class="logo"><a href="{% url 'main:home' %}"><img src="{% static 'resource/ADIMAS.svg' %}" alt="logo"></a></div>
        <div class="menu_navbar">
            <div class="desktop">
                <a href="{% url 'story5:home' %}">List Matkul</a>
                <a href="{% url 'story5:add' %}">Add Matkul</a>
            </div>
            <div class="mobile">
                <a class="burger-button"><img src="/static/resource/burger.svg" alt=""></a>
                <div class="burger-menu burger-hide" id="burger-menu">
                    <a href="{% url 'story4:home' %}">Home</a>
                    <a href="{% url 'story4:poster' %}">My Poster</a>
                </div>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <!-- <footer>
        <p>Copyright ©2020 All rights reserved<br>This website is made by Adimas Putra Pratama Hendrata</p>
    </footer> -->
    <script src="/static/script/main.js"></script>
</body>
</html>

story5/templates/story5/detail.html
{% extends 'story5/baseStory5.html' %}
{% load static %}

{% block content %}

<section>
    <div>
        <a href="{% url 'story5:home' %}"><button class="button" type="submit">Back</button></a>
        <h1>Detail {{ obj.nama_matkul }}</h1>
    </div>

    {% if obj %}
    <table>
        <tr>
            <th><b>Nama Mata Kuliah</b></th>
            <th><b>Dosen Pengajar</b></th>
            <th><b>SKS</b></th>
            <th><b>Semester Tahun</b></th>
            <th><b>Deskripsi</b></th>
            <th><b>Ruang Kelas</b></th>
        </tr>
        <tr>
            <th>{{ obj.nama_matkul }}</th>
            <th>{{ obj.dosen }}</th>
            <th>{{ obj.sks }}</th>
            <th>{{ obj.tahun }}</th>
            <th>{{ obj.deskripsi }}</th>
            <th>{{ obj.ruang }}</th>
        </tr>
    </table>
    {% endif %}
</section>

{% endblock %}

story5/templates/story5/home.html
{% extends 'story5/baseStory5.html' %}
{% load static %}


{% block content %}

<section>
    <h1>Mata KuliahKu</h1>

    
    {% if matkuls %}
    <table>
        <tr>
            <th><b>Nama Mata Kuliah</b></th>
            <th><b>Deskripsi</b></th>
            <th></th>
            <th></th>
        </tr>
        {% for matkul in matkuls %}
        <tr>
            <th>{{ matkul.nama_matkul }}</th>
            <th>{{ matkul.deskripsi }}</th>
            <th><a href="{% url 'story5:detail' my_id=matkul.id %}"><button class="button" type="submit">Detail</button></a></th>
            <th><a href="{% url 'story5:delete' my_id=matkul.id %}"><button class="button" type="submit">Delete</button></a></th>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
        
</section>


{% endblock %}