main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='home'),
]

story4/urls.py
from django.urls import path
from . import views

app_name = 'story4'

urlpatterns = [
    path('', views.story4, name='home'),
    path("poster", views.poster, name='poster'),
    path("website", views.website, name='website')
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.story5, name='home'),
    path('add/', views.add, name='add'),
    path('<int:my_id>/', views.detail, name='detail'),
    path('<int:my_id>/delete/', views.delete_matkul, name='delete'),
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.story6, name='home'),
    path('tambahkegiatan/', views.tambah_kegiatan, name='kegiatan'),
    path('tambah-peserta/<int:id>', views.tambah_peserta, name='add'),
    
]

storyproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("story4/", include('story4.urls')),
    path('', include('main.urls')),
    path('story1/', include('story1.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link
    href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
    rel="stylesheet">
{% endblock meta %}


{% block content %}
<section class="welcome">
    <h1>Welcome to Adimas PPW Story</h1>
</section>

<section class="home-base">
    <div class="pilih">
        <a class="button" href="{% url 'story1:home' %}">Story 1</a>
    </div>

    <div class="pilih">
        <a class="button" href="https://www.figma.com/file/dgiN2gWUAYtbkkv7Oqkt7q/PPW-Story-2?node-id=1%3A148">Story
            2</a>
    </div>
    <div class="pilih">
        <a class="button" href="{% url 'story4:home' %}">Story 4</a>
    </div>

    <div class="pilih">
        <a class="button" href="{% url 'story5:home' %}">Story 5</a>
    </div>

    <div class="pilih">
        <a class="button" href="{% url 'story6:home' %}">Story 6</a>
    </div>

    <div class="pilih">
        <a class="button" href="{% url 'story7:home' %}">Story 7</a>
    </div>

    <div class="pilih">
        <a class="button" href="{% url 'story8:home' %}">Story 8</a>
    </div>

    <div class="pilih">
        <a class="button" href="{% url 'story9:home' %}">Story 9</a>
    </div>
</section>
{% endblock %}